#!/usr/bin/env bash
# Generates the Dart bindings for warren-sdk-ffi from the built cdylib.
#
# Prerequisites: a Dart SDK and a uniffi-bindgen-dart whose supported uniffi
# version MATCHES the `uniffi` crate in crates/warren-sdk-ffi/Cargo.toml.
#
# VERSION LOCK (the current blocker): warren-sdk-ffi uses uniffi 0.31. External
# uniffi bindgens are pinned to the uniffi runtime's metadata format, and the
# published `uniffi-bindgen-dart` (0.1.x) targets an OLDER uniffi, so it cannot
# consume a 0.31 library (it errors on the metadata version, or worse emits
# ABI-incompatible glue). Until a uniffi-0.31-compatible Dart generator exists,
# the alternative is flutter_rust_bridge (a different codegen that does not rely
# on the uniffi metadata). Do NOT commit bindings generated by a mismatched tool.
#
# This script is the single source of truth for HOW the binding is produced; it
# is intentionally explicit so the result is reproducible and the generated code
# never drifts from the Rust surface.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../../.." && pwd)"
OUT="$(cd "$(dirname "$0")/.." && pwd)/lib/src/generated"
mkdir -p "$OUT"

# 1. Build the release cdylib (per-OS artifact name differs).
( cd "$ROOT" && cargo build -p warren-sdk-ffi --release )

case "$(uname -s)" in
  Linux)  LIB="$ROOT/target/release/libwarren_sdk_ffi.so" ;;
  Darwin) LIB="$ROOT/target/release/libwarren_sdk_ffi.dylib" ;;
  *)      LIB="$ROOT/target/release/warren_sdk_ffi.dll" ;;
esac

# 2. Generate the Dart bindings from the library metadata.
uniffi-bindgen-dart generate --library "$LIB" --out-dir "$OUT"

echo "Generated Dart bindings into $OUT"
echo "Bundle $LIB with the app and load it via lib/warren_sdk.dart."
